package edu.ateneo.nrg.kaitai.network;
// This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

import io.kaitai.struct.KaitaiStruct;
import io.kaitai.struct.KaitaiStream;

import java.io.IOException;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.nio.charset.Charset;


/**
 * @see <a href="https://wiki.wireshark.org/Development/LibpcapFileFormat#Record_.28Packet.29_Header">Source</a>
 * 
 * @author zenon
 * 
 * This file was generated by the kaitai struct compiler.
 * Although it may be edited to suit your needs, please
 * refer to @see <a href="http://kaitai.io/</a> for more
 * details on the kaitai struct library and how it can be 
 * used to parse binary files.
 * 
 */
public class Packet extends KaitaiStruct {
    public static Packet fromFile(String fileName) throws IOException {
        return new Packet(new KaitaiStream(fileName));
    }

    public Packet(KaitaiStream _io) {
        super(_io);
        this._root = this;
        _read();
    }

    public Packet(KaitaiStream _io, KaitaiStruct _parent) {
        super(_io);
        this._parent = _parent;
        this._root = this;
        _read();
    }

    public Packet(KaitaiStream _io, KaitaiStruct _parent, Packet _root) {
        super(_io);
        this._parent = _parent;
        this._root = _root;
        _read();
    }
    private void _read() {
        this.tsSec = this._io.readU4le();
        this.tsUsec = this._io.readU4le();
        this.inclLen = this._io.readU4le();
        this.origLen = this._io.readU4le();
    }
    private long tsSec;
    private long tsUsec;
    private long inclLen;
    private long origLen;
    private Packet _root;
    private KaitaiStruct _parent;
    public long tsSec() { return tsSec; }
    public long tsUsec() { return tsUsec; }

    /**
     * Number of bytes of packet data actually captured and saved in the file.
     */
    public long inclLen() { return inclLen; }

    /**
     * Length of the packet as it appeared on the network when it was captured.
     */
    public long origLen() { return origLen; }
    public Packet _root() { return _root; }
    public KaitaiStruct _parent() { return _parent; }
}
